# Generated by Django 3.1.6 on 2021-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('product_name', models.CharField(max_length=25)),
                ('offer', models.CharField(max_length=25)),
                ('shop_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'offer',
                'managed': False,
            },
        ),
    ]
