# Generated by Django 3.1.6 on 2021-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('logid', models.IntegerField()),
                ('shop_name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
    ]
