# Generated by Django 3.1.6 on 2021-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=1000)),
                ('email', models.CharField(db_column='Email', max_length=1000)),
                ('subject', models.CharField(db_column='Subject', max_length=1000)),
                ('message', models.CharField(db_column='Message', max_length=1000)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
