# Generated by Django 3.1.6 on 2021-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('logid', models.IntegerField()),
                ('name', models.CharField(db_column='NAME', max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('municipality_panjayath', models.CharField(db_column='municipality/panjayath', max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'channel',
                'managed': False,
            },
        ),
    ]
