# Generated by Django 3.1.6 on 2021-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
